# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f375689083c699dfa711d4b84ad8dd81ad83cb457f9982cfd729579d190af00da73fbd4997af2cb6b327de50fc9b0c769bb2d14e9c1cb933755c95abf2d8e0db

test:
  secret_key_base: 1d64fa9e6a0cfee3e998e250fe7127870c29b1ba11a2bb3ceece7e6b79bbd4c90d75dff58267229bf288661edcd21943dc6565c6bc9d7f8c4da10f4459e77188

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
